### PR TITLE
ADD: filter for mailing lists

### PR DESCRIPTION
**Pull request by witchi**
Mailing list send a mail header "list-post", which I use to filter such messages into specific folders. This patch adds the functionality to define "list-filters" and search a pattern within the "list-post" header.

### CODE REVIEW

**Comment by 6ec123321** [comment]
“List-post” - what does this mean? What is it for?

**Comment by 6ec123321** [comment]
Give an example of a letter in which you want to filter the desired data.

**Comment by 6ec123321** [comment]
OK. I understood.
```
Mailing list send a mail header "list-post", which I use to filter such messages into specific folders. This patch adds the functionality to define "list-filters" and search a pattern within the "list-post" header.
```
$config['spam_headers'] = array('**list-post**','X-Spam-Flag','X-Spam-Status','X-Yandex-Spam');

**Comment by witchi** [comment]
Ahhh, I see. I added this functionality several times in the last years for different versions of your filter plugin on my own servers. The spam_headers is new, so I'm too late with my patch :-)

**Pull request closed without merging**
